### ISSUE TITLE
Requests too many permissions

### ISSUE THREAD

**Issue by seanf** [sachinjain024/stackeye#52]
Since https://github.com/sachinjain024/stackeye/commit/571069e91110a183c4e20155d64523344ba60123 this extension has been requesting access to all web pages, instead of just Stack Overflow, Stack Exchange and so on.  From a security point of view, this is far too broad for a Stack Exchange-specific extension. 

As far as I can tell, the previous URL patterns (see the commit above) covered all the Stack Exchange sites which currently exist. Please go back to the more restrictive permission set!

Thanks!

PS not sure if this might help with handling new Stack Exchange sites (or Stack Overflow Enterprise sites): https://developer.chrome.com/apps/permissions#request

**Comment by seanf** [comment]
For now, my workaround is to override the permissions for the extension on the settings page to "On specific sites", with these "Allowed sites":

```
https://*.askubuntu.com/*
https://*.mathoverflow.net/*
https://*.serverfault.com/*
https://*.stackapps.com/*
https://*.stackexchange.com/*
https://*.stackoverflow.com/*
https://*.superuser.com/*
```

But I don't know if this will be propagated by Chrome Sync.

**Comment by sachinjain024** [comment]
@seanf I have fixed this issue in the commit - https://github.com/sachinjain024/stackeye/commit/02fa7d858d3a78d4072afb6a727b0d50e25e260c And also deployed to chrome store with version 19.1.3.

Please try out the latest version and the problem should be fixed for you.

**Comment by seanf** [comment]
Sorry @sachinjain024 I hadn't seen your last reply. Thanks for getting on to it quickly!

My browser has updated to 19.1.3, but it's still showing the permission "Read your browsing history" "On all sites" when I view the extension details in Chrome. 

I would uninstall and re-install to see if it used the reduced permission set that way, but I'm concerned about losing my data (ie watchlist). Is there some way I can back up my watchlist? Or at least get a list of my watched questions?

**Comment by sachinjain024** [comment]
Hey @seanf I am afraid exporting/importing data from StackEye is not possible yet. This is one of the most asked features and I promise to work on it soon. You can check that the latest code asks permissions for only specific website

https://github.com/sachinjain024/stackeye/blob/master/manifest.json

And I also checked on my machine, it says the same. I am wondering about it.

Please do not uninstall your extension. You would lose all the data that way. I will look into it again.

**Comment by seanf** [comment]
@sachinjain024 Yes, I think your change was fine, and the extension is still working on the expected sites. I just went through most of my other extensions, and it seems like **all** of them say "On all sites", even the site-specific ones. Not sure what to make of that. Maybe I'm just misinterpreting what I'm seeing there.

Anyway, thanks for the fix!

**Comment by sachinjain024** [comment]
@seanf I believe that is safe because if your script is not injected on any other sites than these site exchange sites, then there is no need to duplicate these sites every time. If you have done filtering at the top level then you can safely say "all" every other time.

Let me know if something is wrong.
